- name: remove unavairable repository
  command: mv /etc/apt/sources.list.d/wolfram.list /etc/apt/sources.list.d/wolfram.disabled
    removes=/etc/apt/sources.list.d/wolfram.list
  sudo: true

- name: apt-get update
  apt: update_cache=true
  sudo: true
