- name: apt-get install gcc libusb-dev
  action: apt name={{item}}
  with_items:
  - gcc
  - libusb-dev
  sudo: true

- name: git clone git://github.com/bitplane/temper.git
  git: repo=https://github.com/bitplane/temper.git
       dest={{temper_dir}}

- name: make temper
  command: make
    chdir={{temper_dir}}
    creates=temper
